### ISSUE TITLE
Comapre between old and new versions of search algorithm

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/Team5-Diet-Tracker#152]
As Koby advicesd us last meeting, it will be interesting to comapre the two versions in terms of "successful search" (i.e. , the percentage of results we expected to see, relevant, in relation to the total number of results).
Let X be the total searches, then rate=(successful results)/X.

### tasks for comparing
- [x] make a list of 50-100 items to search, such that they will give a good general view about the search methods

- [x] check manually (as relevance can't be determined automatically) the dealt items in both methods and see the results.

- [x] sum up the results in a few presentation slides , with the numeric results+explanation for the results: what did we get in each method and what we actually expected)

**Comment by shaked-sapir** [comment]
## Items to compare

### Fruits & Vegetables (10)
apple
avocado
banana
broccoli
date
grapes
orange
potato
tomato
watermelon

### Fast-Food and snacks
chips
chocolate
fries
hamburger
pizza

### Meat & Fish
beef
chicken-breast
salmon
steak
tuna
